[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "eopy"
dynamic = ["version"]
description = 'Package for Earth occultation data analysis.'
readme = "README.md"
requires-python = ">=3.10"
license = "MIT"
keywords = []
authors = [
  { name = "xuewc", email = "wcxuemail@gmail.com" },
]
classifiers = [
  "Development Status :: 4 - Beta",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
]
dependencies = [
#  "arviz",
  "astropy",
#  "corner>=2.2.2",
#  "jax",
#  "jaxopt",
  "matplotlib",
#  "iminuit",
  "numpy",
#  "numpyro",
  "pymsis",
  "scipy",
  "tables",
  "tqdm"
]

[project.urls]
Documentation = "https://github.com/wcxve/eopy#readme"
Issues = "https://github.com/wcxve/eopy/issues"
Source = "https://github.com/wcxve/eopy"

[tool.hatch.version]
path = "src/eopy/__about__.py"

[tool.hatch.envs.default]
dependencies = [
  "coverage[toml]>=6.5",
  "pytest",
]
[tool.hatch.envs.default.scripts]
test = "pytest {args:tests}"
test-cov = "coverage run -m pytest {args:tests}"
cov-report = [
  "- coverage combine",
  "coverage report",
]
cov = [
  "test-cov",
  "cov-report",
]

[[tool.hatch.envs.all.matrix]]
python = ["3.10", "3.11"]

[tool.hatch.envs.lint]
detached = true
dependencies = [
  "black>=23.1.0",
  "mypy>=1.0.0",
  "ruff>=0.0.243",
]
[tool.hatch.envs.lint.scripts]
typing = "mypy --install-types --non-interactive {args:src/eopy tests}"
style = [
  "ruff {args:.}",
  "black --check --diff {args:.}",
]
fmt = [
  "black {args:.}",
  "ruff --fix {args:.}",
  "style",
]
all = [
  "style",
  "typing",
]

[tool.ruff]
line-length = 79
target-version = "py310"
format.quote-style = "single"
lint.extend-select = ["Q"]
lint.flake8-quotes.inline-quotes = "single"
lint.ignore = [
    "B028",  # allow warnings without stacklevel
    "C901",  # allow functions with a high complexity
    "E731",  # allow lambda functions
]
lint.ignore-init-module-imports = true
lint.isort.known-first-party = ["eopy"]
lint.isort.combine-as-imports = true
lint.select = [
    "E",  # pycodestyle errors
    "W",  # pycodestyle warnings
    "F",  # pyflakes
    "I",  # isort
    "C",  # flake8-comprehensions
    "B",  # flake8-bugbear
    "UP",  # pyupgrade
]

[tool.coverage.run]
source_pkgs = ["eopy", "tests"]
branch = true
parallel = true
omit = [
  "src/eopy/__about__.py",
]

[tool.coverage.paths]
eopy = ["src/eopy", "*/eopy/src/eopy"]
tests = ["tests", "*/eopy/tests"]

[tool.coverage.report]
exclude_lines = [
  "no cov",
  "if __name__ == .__main__.:",
  "if TYPE_CHECKING:",
]
